config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'home#index'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :case_files
  resources :messages
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/case_file.rb
class CaseFile < ActiveRecord::Base
end

app/controllers/case_files_controller.rb
class CaseFilesController < ApplicationController
  before_action :set_case_file, only: [:show, :edit, :update, :destroy]

  # GET /case_files
  # GET /case_files.json
  def index
    @case_files = CaseFile.all
  end

  # GET /case_files/1
  # GET /case_files/1.json
  def show
  end

  # GET /case_files/new
  def new
    @case_file = CaseFile.new
  end

  # GET /case_files/1/edit
  def edit
  end

  # POST /case_files
  # POST /case_files.json
  def create
    @case_file = CaseFile.new(case_file_params)

    respond_to do |format|
      if @case_file.save
        format.html { redirect_to @case_file, notice: 'Case file was successfully created.' }
        format.json { render :show, status: :created, location: @case_file }
      else
        format.html { render :new }
        format.json { render json: @case_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /case_files/1
  # PATCH/PUT /case_files/1.json
  def update
    respond_to do |format|
      if @case_file.update(case_file_params)
        format.html { redirect_to @case_file, notice: 'Case file was successfully updated.' }
        format.json { render :show, status: :ok, location: @case_file }
      else
        format.html { render :edit }
        format.json { render json: @case_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /case_files/1
  # DELETE /case_files/1.json
  def destroy
    @case_file.destroy
    respond_to do |format|
      format.html { redirect_to case_files_url, notice: 'Case file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_case_file
      @case_file = CaseFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def case_file_params
      params.require(:case_file).permit(:client_id, :name, :matter, :file_no, :date_opened, :date_closed, :location)
    end
end

app/helpers/case_files_helper.rb
module CaseFilesHelper
end

app/views/case_files/_form.html.erb
<%= form_for(@case_file) do |f| %>
  <% if @case_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@case_file.errors.count, "error") %> prohibited this case_file from being saved:</h2>

      <ul>
      <% @case_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.number_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :matter %><br>
    <%= f.text_field :matter %>
  </div>
  <div class="field">
    <%= f.label :file_no %><br>
    <%= f.text_field :file_no %>
  </div>
  <div class="field">
    <%= f.label :date_opened %><br>
    <%= f.date_select :date_opened %>
  </div>
  <div class="field">
    <%= f.label :date_closed %><br>
    <%= f.date_select :date_closed %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/case_files/edit.html.erb
<h1>Editing Case File</h1>

<%= render 'form' %>

<%= link_to 'Show', @case_file %> |
<%= link_to 'Back', case_files_path %>

app/views/case_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Case Files</h1>

<table class="table">
  <thead>
    <tr>
      <th>Client</th>
      <th>Name</th>
      <th>Matter</th>
      <th>File no</th>
      <th>Date opened</th>
      <th>Date closed</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @case_files.each do |case_file| %>
      <tr>
        <td><%= case_file.client_id %></td>
        <td><%= case_file.name %></td>
        <td><%= case_file.matter %></td>
        <td><%= case_file.file_no %></td>
        <td><%= case_file.date_opened %></td>
        <td><%= case_file.date_closed %></td>
        <td><%= case_file.location %></td>
        <td><%= link_to 'Show', case_file %></td>
        <td><%= link_to 'Edit', edit_case_file_path(case_file) %></td>
        <td><%= link_to 'Destroy', case_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Case file', new_case_file_path %>

app/views/case_files/new.html.erb
<h1>New Case File</h1>

<%= render 'form' %>

<%= link_to 'Back', case_files_path %>

app/views/case_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @case_file.client_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @case_file.name %>
</p>

<p>
  <strong>Matter:</strong>
  <%= @case_file.matter %>
</p>

<p>
  <strong>File no:</strong>
  <%= @case_file.file_no %>
</p>

<p>
  <strong>Date opened:</strong>
  <%= @case_file.date_opened %>
</p>

<p>
  <strong>Date closed:</strong>
  <%= @case_file.date_closed %>
</p>

<p>
  <strong>Location:</strong>
  <%= @case_file.location %>
</p>

<%= link_to 'Edit', edit_case_file_path(@case_file) %> |
<%= link_to 'Back', case_files_path %>